%% ============================================================
%% dx/dt = -x + x^3
%% Phase line + vector field + exact region of attraction
%% ============================================================

clear; close all; clc;

font_size = 16;

%% Create figure
figure('Color','w','Position',[100 100 1000 650]);
hold on; box on;

%% ------------------------------------------------------------
%% Plot the vector field: x_dot = -x + x^3
%% ------------------------------------------------------------

x = linspace(-1.6,1.6,1000);
xdot = -x + x.^3;

plot(x,xdot,'LineWidth',2.5);

% Horizontal zero line
yline(0,'k-','LineWidth',1.5);

%% ------------------------------------------------------------
%% Shade the exact region of attraction
%% ------------------------------------------------------------

% Shade x in (-1,1)
x_fill = [-1 1 1 -1];
y_fill = [-3 -3 3 3];

fill(x_fill,y_fill,...
    [0.85 0.92 1],...
    'EdgeColor','none',...
    'FaceAlpha',0.5);

% Bring vector field back to the front
plot(x,xdot,'LineWidth',2.5);
yline(0,'k-','LineWidth',1.5);

%% ------------------------------------------------------------
%% Mark equilibria
%% ------------------------------------------------------------

plot(-1,0,'ko',...
    'MarkerFaceColor','w',...
    'MarkerSize',10,...
    'LineWidth',2);

plot(0,0,'ko',...
    'MarkerFaceColor','k',...
    'MarkerSize',10,...
    'LineWidth',2);

plot(1,0,'ko',...
    'MarkerFaceColor','w',...
    'MarkerSize',10,...
    'LineWidth',2);

%% ------------------------------------------------------------
%% Labels
%% ------------------------------------------------------------

font_size_tex = 20;

text(-1,-0.45,'Unstable',...
    'HorizontalAlignment','center',...
    'Interpreter','latex',...
    'FontSize',font_size_tex);

text(0,-0.45,'Asymptotically stable',...
    'HorizontalAlignment','center',...
    'Interpreter','latex',...
    'FontSize',font_size_tex);

text(1,-0.45,'Unstable',...
    'HorizontalAlignment','center',...
    'Interpreter','latex',...
    'FontSize',font_size_tex);

text(0,2.4,...
    'R(0)=(-1,1)',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',font_size_tex);

%% ------------------------------------------------------------
%% Add phase-line arrows below the graph
%% ------------------------------------------------------------

y_arrow = -2.4;

HeadSize = 1;

% x < -1 : flow left
quiver(-1.35,y_arrow,...
    -0.3,0,...
    0,...
    'k',...
    'LineWidth',2,...
    'MaxHeadSize',HeadSize);

% -1 < x < 0 : flow right
quiver(-0.65,y_arrow,...
    0.3,0,...
    0,...
    'k',...
    'LineWidth',2,...
    'MaxHeadSize',HeadSize);

% 0 < x < 1 : flow left
quiver(0.65,y_arrow,...
    -0.3,0,...
    0,...
    'k',...
    'LineWidth',2,...
    'MaxHeadSize',HeadSize);

% x > 1 : flow right
quiver(1.35,y_arrow,...
    0.3,0,...
    0,...
    'k',...
    'LineWidth',2,...
    'MaxHeadSize',HeadSize);

% Phase line
plot([-1.8 1.8],[y_arrow y_arrow],...
    'k-','LineWidth',1.5);

text(0,y_arrow-0.3,...
    'Phase line',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontSize',font_size_tex);

%% ------------------------------------------------------------
%% Axis formatting
%% ------------------------------------------------------------
set(gca,...
    'FontSize',font_size,...
    'LineWidth',1.5,...
    'Color','w');

xlim([-1.8 1.8]);
ylim([-3 3]);

xlabel('$x$',...
    'Interpreter','latex',...
    'FontSize',24);

ylabel('$\dot{x}=-x+x^3$',...
    'Interpreter','latex',...
    'FontSize',24);

title('$\dot{x}=-x+x^3$: vector field and exact region of attraction',...
    'Interpreter','latex',...
    'FontSize',22);



grid on;

hold off;