%% dx/dt = -x + x^3
% Visualization of phase portrait and exact region of attraction

clear; close all; clc;

font_size = 16;

%% ============================================================
%% Figure 1: Phase line and region of attraction
%% ============================================================

figure('Color','w','Position',[100 100 1000 350]);
hold on; box on;

% Region of attraction shading
x_fill = [-1 1 1 -1];
y_fill = [-0.3 -0.3 0.3 0.3];

fill(x_fill, y_fill, ...
    [0.85 0.92 1], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.8);

% Main state axis
plot([-2.2 2.2],[0 0], ...
    'k','LineWidth',2);

% Equilibria
plot(-1,0,'ko', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',10, ...
    'LineWidth',2);

plot(0,0,'ko', ...
    'MarkerFaceColor','k', ...
    'MarkerSize',10, ...
    'LineWidth',2);

plot(1,0,'ko', ...
    'MarkerFaceColor','w', ...
    'MarkerSize',10, ...
    'LineWidth',2);

% Labels
text(-1,-0.15,'Unstable', ...
    'HorizontalAlignment','center', ...
    'FontSize',font_size);

text(0,-0.15,'Asymptotically stable', ...
    'HorizontalAlignment','center', ...
    'FontSize',font_size);

text(1,-0.15,'Unstable', ...
    'HorizontalAlignment','center', ...
    'FontSize',font_size);

% Region of attraction label
text(0,0.22, ...
    'R(0) = (-1,1)', ...
    'Interpreter','latex', ...
    'HorizontalAlignment','center', ...
    'FontSize',20);

% ------------------------------------------------------------
% Draw arrows indicating direction of the flow
% ------------------------------------------------------------

% x < -1 : flow to the left
quiver(-1.6,0, ...
    -0.35,0, ...
    0, ...
    'k', ...
    'LineWidth',2, ...
    'MaxHeadSize',0.8);

% -1 < x < 0 : flow to the right
quiver(-0.65,0, ...
    0.35,0, ...
    0, ...
    'k', ...
    'LineWidth',2, ...
    'MaxHeadSize',0.8);

% 0 < x < 1 : flow to the left
quiver(0.65,0, ...
    -0.35,0, ...
    0, ...
    'k', ...
    'LineWidth',2, ...
    'MaxHeadSize',0.8);

% x > 1 : flow to the right
quiver(1.6,0, ...
    0.35,0, ...
    0, ...
    'k', ...
    'LineWidth',2, ...
    'MaxHeadSize',0.8);

xlim([-2.2 2.2]);
ylim([-0.3 0.3]);

set(gca, ...
    'FontSize',font_size, ...
    'YTick',[], ...
    'LineWidth',1.5);

xlabel('$x$', ...
    'Interpreter','latex', ...
    'FontSize',20);

title('$\dot{x}=-x+x^3$: phase line and region of attraction', ...
    'Interpreter','latex', ...
    'FontSize',20);

hold off;


%% ============================================================
%% Figure 2: Time trajectories
%% ============================================================

figure('Color','w','Position',[200 200 1000 600]);
hold on; box on;

% Initial conditions inside and outside the ROA
x0_inside  = [-0.9 -0.7 -0.4 0.2 0.5 0.8];
x0_outside = [-1.002 -1.01 -1.05 -1.4 1.002 1.01 1.05 1.4];

% Integration options
options = odeset( ...
    'RelTol',1e-8, ...
    'AbsTol',1e-10, ...
    'Events',@blowup_event);

% ------------------------------------------------------------
% Trajectories starting inside the region of attraction
% ------------------------------------------------------------

for k = 1:length(x0_inside)

    x0 = x0_inside(k);

    [t,x] = ode45( ...
        @(t,x) -x + x^3, ...
        [0 8], ...
        x0, ...
        options);

    plot(t,x, ...
        'LineWidth',2);
end


% ------------------------------------------------------------
% Trajectories starting outside the region of attraction
% ------------------------------------------------------------

for k = 1:length(x0_outside)

    x0 = x0_outside(k);

    [t,x] = ode45( ...
        @(t,x) -x + x^3, ...
        [0 8], ...
        x0, ...
        options);

    plot(t,x, ...
        '--', ...
        'LineWidth',2);
end


% Equilibrium lines
yline(0,'k-', ...
    'LineWidth',1.5);

yline(1,'k--', ...
    'LineWidth',1.5);

yline(-1,'k--', ...
    'LineWidth',1.5);


set(gca, ...
    'FontSize',font_size, ...
    'LineWidth',1.5);

xlabel('$t$', ...
    'Interpreter','latex', ...
    'FontSize',20);

ylabel('$x(t)$', ...
    'Interpreter','latex', ...
    'FontSize',20);

title('Trajectories inside and outside the region of attraction', ...
    'Interpreter','latex', ...
    'FontSize',20);


ylim([-3 3]);

grid on;
hold off;


%% ============================================================
%% Event function: stop integration when trajectory grows large
%% ============================================================

function [value,isterminal,direction] = blowup_event(~,x)

    value = 5 - abs(x);
    isterminal = 1;
    direction = -1;

end