name: Build LaTeX document

on: 
  push:
  pull_request:
    types:
      - closed
    branches:
      - main



jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document ControlTheoryRecap
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: SlidesRU/ControlTheoryRecap/



      - name: Save ControlTheoryRecap artifact
        uses: actions/upload-artifact@v4
        with:
          name: ControlTheoryRecap.pdf
          path: SlidesRU/ControlTheoryRecap/main.pdf





      - name: Update compiled PDFs in git repository
        if: github.event.pull_request.merged == true || github.event_name == 'push'
        run: |
          mv SlidesRU/ControlTheoryRecap/main.pdf SlidesRU/ControlTheoryRecap.pdf

          
          git config --global user.name 'CI PDF compiler'
          git config --global user.email '<>'
          git add SlidesRU/ControlTheoryRecap.pdf



          git commit -m "Update compiled PDFs"
          git push
